### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Pierre1533** [redphx/better-xcloud-android#101]
### Device

Phone/Tablet

### Device name

REDMI NOTE 11

### Android Version

13

### App version

0.15.1

### Script version

4.6.3

### WebView name and version

Aplicativo para Android 

### Reproduction Steps

Better xcloud, there is a bug in the image in the game hellblade 2, my better xcloud is ok, I updated it, I also tested the old versions but I still can't play, fix this please ❤️ Your work is incredible.

https://github.com/redphx/better-xcloud-android/assets/125102747/614e484b-7480-4fb4-a0d1-82b24a145368

**Comment by redphx** [comment]
Check the latest version
