### ISSUE TITLE
[Bug] App closes on start up

### ISSUE THREAD

**Issue by Tunim163** [redphx/better-xcloud-android#102]
### Device

Phone/Tablet

### Device name

Motorola Moto e22

### Android Version

12

### App version

0.16.0

### Script version

I don't remember it's probably the most updated version

### Reproduction Steps

Application does not open

**Comment by redphx** [comment]
Re-download the app. Old version had a bug.

**Comment by Tunim163** [comment]
![1000019326](https://github.com/redphx/better-xcloud-android/assets/172115505/e3d36fad-9c66-43e0-8597-ac49520409ec)

**Comment by Tunim163** [comment]
> Re-download the app. Old version had a bug.

Ok
