### ISSUE TITLE
[Bug] App settings icon overlaps the search shortcut

### ISSUE THREAD

**Issue by piersandro** [redphx/better-xcloud-android#103]
### Device

Phone/Tablet

### Device name

Logitech G Cloud

### Android Version

Android 11

### App version

0.16.0

### Script version

4.7.0

### WebView name and version

Android System WebView 125.0.6422.165

### Reproduction Steps

I noticed that the app settings icon overlaps with the search shortcut indication.

How to reproduce:
1) Open xCloud App
2) Navigate on the interface via the controller buttons
3) Scroll down and up
4) The Settings icon will overlaps with the search shortcut indication.

![telegram-cloud-photo-size-4-5989848514869445358-x](https://github.com/redphx/better-xcloud-android/assets/19996309/b5689898-a489-479f-b8e1-cff1ab269755)

The search shortcut is not viewable if you scroll with the touchscreen.

**Comment by piersandro** [comment]
I think in part is a duplicate of this enhancement request: https://github.com/redphx/better-xcloud-android/issues/93

**Comment by KingNothing81** [comment]
> I think in part is a duplicate of this enhancement request: #93

Hi ... That's my enhancement request. And on your shared screenshot I can see that you also don't have a refresh button on top of the settings button? So why do I have one? 

@redphx: Does the refresh button only show up on Android TV? Because as I need a mouse to press that button, I could also just use "pull to refresh". Because that also works with a mouse if you press and hold the left mouse button at the top of the page and then pull down.

**Comment by piersandro** [comment]
> Hi ... That's my enhancement request. And on your shared screenshot I can see that you also don't have a refresh button on top of the settings button? So why do I have one?

I use Logitech G Cloud. Essentially it's an Android tablet with an attached controller. 
The refresh button I this is missing because the device have a built-in touch screen.

**Comment by redphx** [comment]
This is not really an issue because the Settings button only blocks the shortcut when you're at the top of the page. When scrolling down the search shortcut is still there, so users can still see it.  
Fixing it will break the UI and I don't like it.

**Comment by piersandro** [comment]
Ok, but moving the settings icon to the left could be a solution.

**Comment by KingNothing81** [comment]
> Ok, but moving the settings icon to the left could be a solution.

Hm, but if it's on the left side, it will be in "conflict" with the Xbox Guide menu. ;)

My suggestion was to do those things with an app dialog box that shows up on the screen if the user presses Android's Back button (as every Android (TV) device has one). And that would include all needed options like "open app settings", "refresh page", "quit app" and maybe "check for updates". So you can check for pending updates without having to close and reopen the app first.

**Comment by piersandro** [comment]
> Hm, but if it's on the left side, it will be in "conflict" with the Xbox Guide menu. ;)

No, it depends on z-index level. It could be covered when the Guide is opened. 
But my point of view is as an handheld user.
