### ISSUE TITLE
[Bug] Unreadable text in the app settings after updating to 0.16

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud-android#104]
### Device

Other

### Device name

Shield TV

### Android Version

Android TV 11

### App version

0.16

### Script version

4.7.0

### WebView name and version

Chrome 125.x

### Reproduction Steps

Since updating to version 0.16, most text in the app settings window is not readable anymore, as it’s shown dark on a dark background.

![PNG-Bild2](https://github.com/redphx/better-xcloud-android/assets/146887651/eef8ad0a-308d-48b5-9f9e-9b60861b2a80)

I guess this was caused by adding the option to switch between a light and dark theme. And the app seems to use the light theme on Android TV now. As dialog boxes like this have a white background now, but had a dark one before the update. 

![PNG-Bild](https://github.com/redphx/better-xcloud-android/assets/146887651/a9a56143-45b7-4fc5-86f0-faf68ba0b68e)

Android TV doesn’t have a system wide setting to choose between a light and dark theme as your default. So sideloaded apps that support both, will always default to using the light theme on Android TV. 

So I think the easiest solution would be to enforce the dark theme on Android TV. Or if you like, to also show the theme option in the app settings on Android TV. So Android TV users could also switch between a light and dark theme.

**Comment by redphx** [comment]
Fixed in 0.16.1

**Comment by KingNothing81** [comment]
Thanks for the quick fix. But now the settings window has a white background.

![PNG-Bild](https://github.com/redphx/better-xcloud-android/assets/146887651/5311d3e7-aedf-4231-8a88-52b8ffffb0fa)

I really preferred the dark background and app dialogs. Especially for TVs I think it’s always better to keep UI’s dark. The light theme is just too bright for the big screen in my opinion.

But it’s a matter of taste of course. That’s why I  suggested to also show the theme option in the app settings on Android TV. So users can decide for themselves. But if you don’t want to do that, I hope you can consider using a dark theme on Android TV again. 

Thanks.
