### ISSUE TITLE
[Bug] No controller vibration on Razer Kishi V2 Pro

### ISSUE THREAD

**Issue by 1219jjh** [redphx/better-xcloud-android#106]
### Device

Phone/Tablet

### Device name

Samsung S22

### Android Version

14

### App version

0.16.1

### Script version

4.7.1

### Reproduction Steps

Can't recognize controller vibration on Razer Kishi V2 Pro.

Controller supports vibration and works on xbox cloud in razer nexus, but not working on better xcloud.

**Comment by redphx** [comment]
Test vibration using App settings > Links > Gamepad tester
