### ISSUE TITLE
[Bug] Swipe down close the game

### ISSUE THREAD

**Issue by Aendros** [redphx/better-xcloud-android#108]
### Device

Phone/Tablet

### Device name

Poco X6 pro

### Android Version

14

### App version

0.16.2

### Script version

4.7.1

### WebView name and version

125.0.6422

### Reproduction Steps

Not always works: 
1. Start a Game remote or xcloud
2. Play for a little 
3. Swipe down from top left corner or top right córner
The Game closes and return to home screen

**Comment by redphx** [comment]
Video?
