### ISSUE TITLE
[Bug] It is judged to be a malicious app and cannot be installed 

### ISSUE THREAD

**Issue by chs3112** [redphx/better-xcloud-android#109]
### Device

Phone/Tablet

### Device name

Samsung Galaxy Z Flip 5 

### Android Version

14

### App version

0.16.2

### Script version

4.7.1

### Reproduction Steps

When I try to install it, it is not installed because it is a malicious app suspected of voice phishing.

**Comment by redphx** [comment]
It's a false-positive report: https://www.virustotal.com/gui/file/fc4e43b13d893bbb0ba2b1a9f0dd20dd775fbbbb25141d3646ed30b18239485e
