### ISSUE TITLE
[Bug] Draining a lot of energy 

### ISSUE THREAD

**Issue by darkSTONP** [redphx/better-xcloud-android#11]
The app is using a lot of battery, in 1 hour of use with low brightness, the app used almost 25% of battery, a much higher usage than the Kiwi browser.

![Screenshot_2024-03-17-02-37-22-187_com miui securitycenter](https://github.com/redphx/better-xcloud-android/assets/124324337/fef58e84-0875-4df5-958e-4852d5b18c6a)

**Comment by darkSTONP** [comment]
My phone is a poco m4 pro 5g Mali G57 MC2

**Comment by redphx** [comment]
If you see this message in version 0.3 then use Kiwi instead.  

![telegram-cloud-photo-size-5-6328107245610582664-y](https://github.com/redphx/better-xcloud-android/assets/96280/3fe328d5-2f8e-4c55-9e11-db53d15c2ce5)

**Comment by redphx** [comment]
#41
