### ISSUE TITLE
[Bug] Strange green button with circled arrow is always visible on right-bottom corner of the screen

### ISSUE THREAD

**Issue by slajerek** [redphx/better-xcloud-android#114]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [x] xCloud officially supports my country/region.
- [x] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

TV

### Device

NVidia Shield

### Operating System

Android

### Android app/Browser Version

NVidia Shield

### Better xCloud Version

5.0.1

### Reproduction Steps

1. Start game
2. There's always visible strange button on right-bottom side of the screen with circled arrow
3. It is not possible to click on this button using game pad, nor TV remote. 
4. It is also not possible to remove this button and make it invisible.
5. Button stays permanently on screen and can not be moved.
6. Button overlaps sometimes important information and hides what's beneath.

This button should not be visible, not sure what it is actually and from where it is.

### Screenshot/video

<img width="987" alt="Screenshot 2024-06-30 at 13 24 27" src="https://github.com/redphx/better-xcloud/assets/1021783/6dee688f-4699-40b7-9f07-6b82d604ef0e">

<img width="990" alt="Screenshot 2024-06-30 at 13 26 15" src="https://github.com/redphx/better-xcloud/assets/1021783/d0577b20-fc67-4389-887d-9d9d4ce0dc20">

**Comment by redphx** [comment]
This happens when the script isn't being loaded (no server name at the top right of the screen) but you still play a game. When it happens refresh the page manually to fix it.

Version 0.16.3 also hides the Refresh button even when the script is not running.
