### ISSUE TITLE
[Bug] Controller vibration not working

### ISSUE THREAD

**Issue by Tonhos** [redphx/better-xcloud-android#117]
### Device

Phone/Tablet

### Device name

Samsung Galaxy S20 FE

### Android Version

13

### App version

0.16.2 (22)

### Script version

5.1.1

### WebView name and version

Android System WebView 126.0.6478.134

### Reproduction Steps

![BXC](https://github.com/redphx/better-xcloud-android/assets/126985424/fdb9ef77-a8d2-408f-a704-cd417882a71d)

I connected my Xbox Series controller multiple times, reinstalled the Better xCloud App twice, and checked the vibration settings, and still, the app doesn't seem to turn on the vibration

https://github.com/redphx/better-xcloud-android/assets/126985424/e39ae62d-b393-4a2c-a94d-9405e4e6d29d

**Comment by redphx** [comment]
Xbox controller's vibration only works in wired mode
