### ISSUE TITLE
[Bug] Crashing/Cannot open Android app after recent update

### ISSUE THREAD

**Issue by RC1992Jules** [redphx/better-xcloud-android#118]
### Device

Phone/Tablet

### Device name

OnePlus Pro 5G

### Android Version

14

### App version

0.16.3

### Script version

Unknown 

### Reproduction Steps

After downloading and installing the latest update I am no longer able to open the app. I tried uninstalling the app and reinstalling but the same error occurs where I get the Xbox logo splash screen and then the app closes and my phone returns to the homepage.

**Comment by redphx** [comment]
Fixed, just re-download and reinstall

**Comment by RC1992Jules** [comment]
Awesome, thank you!
