### ISSUE TITLE
[Feature] App icon

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud-android#12]
The app will have a new icon later

**Comment by KingNothing81** [comment]
Is the app supposed to show up on the Android TV launcher already? 
Because it doesn't for me.

**Comment by flipside101** [comment]
> Is the app supposed to show up on the Android TV launcher already? Because it doesn't for me.

Same here , No app icon on the  AndroidTV launcher

**Comment by KingNothing81** [comment]
@flipside101: As a temporary solution you can create your own app launcher using that website:

https://atvlauncher.trekgonewild.de/

The package name you need to use is:
com.redphx.betterxc

**Comment by KingNothing81** [comment]
Correction … It’s already there on Android TV. But with a completely black icon. So if it’s at the end of your apps grid, you won’t see it. ;)

![IMG_0247](https://github.com/redphx/better-xcloud-android/assets/146887651/3f7554be-5705-4492-aa5f-b8ac75b5df4a)

**Comment by redphx** [comment]
Added in 0.10.1
