### ISSUE TITLE
[Bug] B Button doesn't work on App Version

### ISSUE THREAD

**Issue by UNKN0WNUSER94** [redphx/better-xcloud-android#120]
### Device

Other

### Device name

Logitech G Cloud

### Android Version

11

### App version

0.16.4

### Script version

n/a

### Reproduction Steps

I use the Logitech G Cloud as a device. 
The problem in the app is that the B button is not recognized. 
There are no problems with the Kiwi browser and everything works perfectly there.

**Comment by redphx** [comment]
Only in-game or everywhere?  
This is the first time I hear about this bug, and I have a G Cloud myself.

**Comment by UNKN0WNUSER94** [comment]
It does not work anywhere, even in the menu it does not recognize it.

**Comment by redphx** [comment]
Something must be wrong with your device
