### ISSUE TITLE
[Feature] Use Create Shortcut with the controller instead of the touch screen

### ISSUE THREAD

**Issue by piersandro** [redphx/better-xcloud-android#123]
### Device

Phone/Tablet

### Device name

Logitech G Cloud

### Android Version

11

### Suggestion

I have noticed that some features of the Android application can only be reached with the touch screen.
The script added some buttons in the Xbox Cloud Help menu, would it be possible to move (for example) the one for creating a Shortcut next to the Buy button to make it usable with the controller without necessarily using the touch screen? This would also benefit Smart TV users.

![image](https://github.com/user-attachments/assets/7206a28f-f2ef-408f-9d57-f518bd8d78ab)

The button is currently overlayed, it could become an integrated element in the interface.

**Comment by redphx** [comment]
Added in 0.17.0
