### ISSUE TITLE
[Feature] Create a shortcut by pressing the X button on the controller from games lists

### ISSUE THREAD

**Issue by piersandro** [redphx/better-xcloud-android#124]
### Device

Phone/Tablet

### Device name

Logitech G Cloud

### Android Version

11

### Suggestion

In the Xbox Cloud main screen but also in the lists of available games (by category or all games), it would be useful to be able to create a shortcut by pressing the X button on the controller and having a pop-up appear asking you to confirm whether or not you want to create it.
It would be convenient to be able to create a shortcut without necessarily having to enter the game page.

**Comment by redphx** [comment]
I'd prefer only implementing #123

**Comment by piersandro** [comment]
> I'd prefer only implementing #123 

Ok, but consider that a function like this could be useful for recently opened games list (that launches the games automatically and doesn't show the game page). 

Thanks.
