### ISSUE TITLE
Remove “Enable Better xCloud script” toggle in app settings

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud-android#125]
### Device

Other

### Device name

Shield TV

### Android Version

Android TV 11

### Suggestion

Hi … 

I really like that the bottom right buttons are gone now. But I think there is an option now in the app settings that could cause some trouble: The “Enable Better xCloud script” toggle.

Because maybe I’m wrong, but I think all buttons to open the app settings are generated by the script now? So if the user disables script injection, there is no way back to the app settings to enable it again.

So I think the quickest and easiest solution would be to just remove the option. 

Or another idea to bypass the problem: At the moment you show a toast message when the user presses the back button on the home screen. But how about showing a real confirmation prompt asking “Do you really want to close the app?”. And that also has an “open app settings” button beside OK/Cancel. Like this there would be way to go to the app settings that’s independent from the script (as a backup solution).

Thanks.

**Comment by redphx** [comment]
The App settings button will be shown at bottom-right corner when Better xCloud script is disabled

**Comment by KingNothing81** [comment]
Ah, ok. Sorry, I didn't want to give it, because I was not sure that I wouldn't have to reset the app to get back to the app settings. But of course you were already aware of the potential problem and solved it. =)
