### ISSUE TITLE
[Bug] "Please update your FireTV" when launching

### ISSUE THREAD

**Issue by PhunkyBob** [redphx/better-xcloud-android#127]
### Device

Other

### Device name

Amazon FireTV 4K

### Android Version

FireOS 7

### App version

0.17.0

### Script version

?

### WebView name and version

?

## Steps to reproduce
- Download `com.redphx.betterxc_0.17.0-25.apk` from this repo.
- Copy to FireTV.
- Install APK.
- Open the installed application.

## Expected behavior
- Ask for login / password.
- Show Xbox Cloud gaming interface.

## Actual behavior
- A message says "update your FireTV".

When I go to my FireTV parameters and search for an update, it says that I'm already up-to-date.

## Additional information
- I don't have the latest version of Amzon FireTV 4K but the previous one. 
- I can't install Xbox application from store. I installed it from APK 2 weeks ago and it worked.
- 2 weeks ago, Xbox application and Better Xcloud worked fine.
- When I install the Xbox APK, today I have the same message and I can't use it.

**Comment by redphx** [comment]
Try [0.18.0-beta](https://github.com/redphx/better-xcloud-android/releases/tag/a0.18.0-beta)

**Comment by PhunkyBob** [comment]
Same message with `com.redphx.betterxc_0.18.0-beta-25.apk` :(

**Comment by redphx** [comment]
The website requires Amazon Silk 122 or later. Try to update if you can.  

I though I fixed it in the beta version but it didn't work because of a WebView bug. I'll find a fix later.

**Comment by PhunkyBob** [comment]
I checked the version of Silk : it's already 122. There is no update available in the store.
I tried to install manually an APK of version 124, but I always have the same message...

**Comment by redphx** [comment]
What is your user-agent in https://whatmyuseragent.com/

**Comment by PhunkyBob** [comment]
My user agent is: 
`Mozilla/5.0 (Linux; Android 9; AFTKA) AppleWebKit/537.36 (KHTML, like Gecko) Silk/124.5.2 like Chrome/124.0.6367.248 Safari/537.36`

**Comment by PhunkyBob** [comment]
Following an external advice, I downgraded my Webkit from 122.4.2.6261.160.30 to 122.6261.140.58, and it works.

**Comment by redphx** [comment]
Should be fixed in beta-2: https://github.com/redphx/better-xcloud-android/releases/tag/a0.18.0-beta-2  

it's recommended to use Thorium and Enable "optimize webview" feature

**Comment by redphx** [comment]
Fixed in 5.5.3
