### ISSUE TITLE
[Feature] Enable mic into game

### ISSUE THREAD

**Issue by Zxteckin** [redphx/better-xcloud-android#13]
**I'm using:**  
- Device name: ...Samsung 
- Device type (phone/TV): ... Samsung A6+
- Android version: ...
  10
**I want to suggest this feature:**  
...
I was playing Fortnite and when trying to activate the microphone in the adjustment tab within the game this feature, it simply does not activate, due to the need to give authorization to access the microphone, like It is done in the Kiwi Browser app, natively.

**Comment by redphx** [comment]
There is a test version in telegram channel: https://t.me/betterxcloud

**Comment by redphx** [comment]
Duplicate #5
