### ISSUE TITLE
[Feature] Keep Zoom Factor During Gameplay

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud-android#135]
### Device

TV

### Device name

NVIDIA Shield TV

### Android Version

Android TV 11

### Suggestion

Hi …

I’m using the app on a 1080p display. And always found that xCloud’s UI is just too big for a FullHD TV.

For the home page I can lower the page zoom factor in the app settings. But when starting a game, it returns to 100%. And everything is too big again for my taste.

So I wanted to ask if it’s possible to also keep the zoom factor during gameplay.

I also reduced the page zoom factor when I still used Kiwi Browser. And it didn’t cause any issues for me.

So if this doesn’t create problems for touch users, I would really prefer if the page zoom factor would also be applied during gameplay. Or maybe it’s at least possible to make this an additional option by adding a checkbox?

Thanks.

**Comment by redphx** [comment]
Added in 0.20.1

**Comment by KingNothing81** [comment]
> Added in 0.20.1

Thanks. You are great.

But one related thing I wanted to ask: 

I really like the look of the "floating" Guide menu of the "Smart TV" layout. But even going down to 80% zoom factor, it's still unusuable big on a 1080p display.

So I wonder how is the situation on Fire TV's and the official app? That seems to use the same UI like Samsung Smart TVs. But when the Fire TV is set to 1080p output and you use the official app, is the UI also shown in gigantic size? If not, and the UI scales down right, maybe it's to adapt this and use the Fire TV UI as "Smart TV" layout? So it will also look fine on 1080p displays.

Or as an alternative: Allow lower values for the page zoom factor, so I might be able to shrink things down myself.

Thanks.
