### ISSUE TITLE
[Feature] AutoUpdate Better xCloud Script on start-up

### ISSUE THREAD

**Issue by piersandro** [redphx/better-xcloud-android#136]
### Device

Phone/Tablet

### Device name

Logitech G Cloud

### Android Version

11

### Suggestion

I would propose a search for the latest version of the script and the subsequent automatic installation at application start-up.
Currently, the manual procedure is uncomfortable as there is no ‘Update’ button provided in the Better xCloud menu, but it is necessary to go to Application Settings, and scroll down to Update Better xCloud Script.
After the update, the app with a popup may still warn of the update and offer a link to the changelog.

**Comment by redphx** [comment]
Added in 0.20.1
