### ISSUE TITLE
[Bug] No installation prompt after downloading an update anymore

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud-android#137]
### Device

Other

### Device name

Shield TV

### Android Version

Android TV 11

### App version

0.20.1

### Script version

5.7.3

### WebView name and version

Android System WebView

### Reproduction Steps

Hi ...

I don't know if this is really a bug or an intended change:

But in the past, when the app had finished downloading an update, the app always showed the Android installation prompt, asking if you want to install the update. 

But for a while now, the app only shows a toast message with the download location when the download has finished.

So to install the APK you have to open the download folder and install the update yourself. I think this can be problematic, as Android TV and Fire TV devices don't come with a file explorer installed by default. And not all users might be familiar with using one. But apart from that, I think it also makes installing updates less easy and comfortable.

So if this is was an intended change, maybe you can consider rolling it back.

Thanks.

**Comment by redphx** [comment]
Works fine on every devices I own

**Comment by KingNothing81** [comment]
Hm ... that's strange. Because it also worked on mine device in the past. Unfortunately I can't remember since what app version the behaviour changed. But now there is only a toast message showing the download directory when the file has finished downloading.

Did you add that toast message? Because it wasn't there when the installation prompt still showed up. If that's the case, I guess the addition of the toast message somehow prevents the installation prompt. Which might be not the case on more recent Android versions or non-TV devices?

But if this only affects me or a small number of users, it's also not a big problem to manually install the APK files from now on.
