### ISSUE TITLE
[Bug] Server / Remote play missing

### ISSUE THREAD

**Issue by phantomdenied** [redphx/better-xcloud-android#14]
**Platform**
- Device name:  Meta Quest 2
- Device type (phone/TV):  VR
- Android version: 
- App version: 0.1
- Script version: 

**Describe the bug** After sign in server /  remote play buttons do not appear in app. 

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by redphx** [comment]
Make sure this app is up-to-date: https://play.google.com/store/apps/details?id=com.google.android.webview

**Comment by BigFrog666** [comment]
I'm having the same problem after switching wifi network

**Comment by BigFrog666** [comment]
https://github.com/redphx/better-xcloud-android/assets/163888827/af372a81-0dbf-455b-a03a-ee1219b5f3f0

Screen Recording with the Issue

**Comment by redphx** [comment]
@BigFrog666 you need to open port 9002 https://better-xcloud.github.io/remote-play/

**Comment by redphx** [comment]
@phantomdenied you can try sideloading from APK Mirror

**Comment by phantomdenied** [comment]
@redphx Sorry, I should of mentioned I did that. Installed via Kiwi. Hard reset often install. No luck.

**Comment by redphx** [comment]
Install 0.3 and see if it shows any "Unsupported" dialog

**Comment by BigFrog666** [comment]
> @BigFrog666você precisa abrir a porta 9002 https://better-xcloud.github.io/remote-play/

In the default app, this isn't necessary, it works without it. Could you explain to me why in the case of better xcloud it is?

**Comment by BigFrog666** [comment]
> @BigFrog666 you need to open port 9002 https://better-xcloud.github.io/remote-play/

Even with the door open, the error continues

**Comment by redphx** [comment]
@phantomdenied try Settings > Update Better xCloud script

**Comment by BigFrog666** [comment]
> @BigFrog666 you need to open port 9002 https://better-xcloud.github.io/remote-play/

The error persists even with the doors open

**Comment by phantomdenied** [comment]
@redphx the auto update still does not work (meta quest). On app open the update is displayed, I accept, a small blank text box appears at the bottom then the app crashes about 5 seconds later. Trying to update through the settings, it just sits there at the menu. 
v 0.3 displays the unsupported dialog. Latest Android Webview was installed from pureAPK.

**Comment by redphx** [comment]
Does the Quest have the "Developer settings" similar on the phone? If it does, what does it say in the "WebView implementation" screen?

**Comment by phantomdenied** [comment]
The developer options do not include a WebView tab.

**Comment by redphx** [comment]
Meta Quest doesn't support Android WebView so Better xCloud app won't work on these devices.

**Comment by redphx** [comment]
Move to #55

**Comment by phantomdenied** [comment]
Can confirm that using the Chrome linked (arm64) worked. Installed it, reset, set to new chrome webview and everything worked on Meta Quest 2.
