### ISSUE TITLE
[Bug] Decode time too high on fire tv.

### ISSUE THREAD

**Issue by sachinpatl** [redphx/better-xcloud-android#140]
### Device

TV

### Device name

Fire TV 4k Max

### Android Version

11

### App version

0.21.0

### Script version

5.8.2

### WebView name and version

Amazon System WebView 124.amazon-webview-v124-6367-tv.6367.248.109

### Reproduction Steps

I have been trying better xcloud on my FireTV as well as on my laptop. 
First I thought it's bad but later I realized it's working fine on laptop but is slow on my TV only.
Then I started to monitor the stats and compared those on TV vs those on laptop. 

Then I realised the Decode Time on my laptop is around 1 - 1.5 ms. However this time on TV is 55 to 60ms.

Need help in resolving this. I tried the option in application setting to improve performance on TVs but it did not help much.

Now the Decode time has come down to 45 ms but is still too slow and I can feel the performance difference in TV vs Laptop.

**Comment by redphx** [comment]
1. Decode time is bugged on Android https://github.com/redphx/better-xcloud/issues/26  
2. There is nothing you can do about it. Everything has system requirements.

**Comment by sachinpatl** [comment]
Also I might be going in wrong direction here by looking at the Decode Time, but is that the only reason for input lag being so bad on TV. I have noticed that even the while navigating the store I see input lag and miss key presses.
