### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sachinpatl** [redphx/better-xcloud-android#141]
### Device

TV

### Device name

Fire TV 4k Max

### Android Version

11

### App version

0.21.0

### Script version

5.8.2

### WebView name and version

Amazon System WebView 124.amazon-webview-v124-6367-tv.6367.248.109

### Reproduction Steps

The input lag is too bad on the TV app on Fire TV 4k Max.

Sorry for opening another issue on the same day, but I just realized I had opened a wrong bug after reading @redphx answer on it.
So the issue is not with the stream / decoding, the issue is with the input lag. 

The TV app is missing inputs key strokes and lagging as well.

I just compared the TV and Laptop the controller works just fine while traversing / navigating the store. But when I do the same on TV it sometimes misses keystrokes and sometimes lags.

**Comment by redphx** [comment]
Tv problem

**Comment by sachinpatl** [comment]
I digged a little more and realized there is ALLM mode in fire tv stick as well. Can we add a note to the setup guide to remember to enable game mode / auto low latency mode so that folks don't struggle similar to how I did.
