### ISSUE TITLE
[Feature] Remote play for controller only

### ISSUE THREAD

**Issue by GlasSr2346** [redphx/better-xcloud-android#142]
### Device

Phone/Tablet

### Device name

All devices

### Android Version

All version

### Suggestion

Hi, I wanted to propose a function to do remote playback but without video, only control, to be a type of adapter for controllers not directly compatible with Xbox without consuming a lot of battery and Internet, for example I use the 8Bitdo Sn30 pro Xbox, and it is not directly compatible with Xbox so I have to connect it to my phone, and therefore the video is played on the phone, my proposal is to make a zand therefore the video is played on the phone, my proposal is to make a type of "intermediary" that I did not receive the video and I only sent the signal from the controller to the Xbox, many gintermediary" that I did not receive the video and I only sent the signal from the controller to the Xbox, thank you very much 🫶.

**Comment by redphx** [comment]
Use this feature in Game Bar

![bx-hide](https://github.com/user-attachments/assets/994014be-5b28-4636-a5b0-bb3dad3ffd31)
