### ISSUE TITLE
[Bug] the Android app inst  working on my smartphone.

### ISSUE THREAD

**Issue by ItzSage144** [redphx/better-xcloud-android#144]
### Device

Phone/Tablet

### Device name

Poco X6 Pro (12 RAM, Global Version)

### Android Version

14

### App version

0.22.0

### Script version

5.9.5

### WebView name and version

Android System WebView 130.0.6723.86

### Reproduction Steps

The app isn't working on the specific smartphone, I can't login for some reason (it says too many request, I can login on my other phone tho) and I dont have access to the configurations at all. When I say configs it's not the app configurations, it's the script configs/options. I have two phones and on my oldest one (Nokia 5.3) it works perfectly, but on the Poco X6 Pro isn't working, I tried to turn on and off all the app configurations to see if it could help and it's not helping, also I tried to update the WebView and still the same issue and the script is updated. I've been using this amazing app for months and it's the first time a have a issue with it.
![Screenshot_2024-11-07-20-17-38-060_com redphx betterxc](https://github.com/user-attachments/assets/edcba173-8f26-4e47-9d86-c9fa7771e21a)
![Screenshot_2024-11-07-20-17-46-490_com redphx betterxc](https://github.com/user-attachments/assets/42638dfa-2526-4da0-a917-a3926cd9ab5d)
![Screenshot_2024-11-07-20-17-17-146_com redphx betterxc](https://github.com/user-attachments/assets/d9d4c84e-10a1-453b-b458-c0bfcd93c5ac)

**Comment by redphx** [comment]
This is xCloud's problem. You need to log in to use all features. Try VPN and log in.

**Comment by ItzSage144** [comment]
The VPN worked, thank you so much!
