### ISSUE TITLE
[Bug] The app switches my device to 480p output when I open it

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud-android#15]
**Platform**
- Device name: Shield TV
- Device type (phone/TV): Android TV
- Android version: 11
- App version: 0.1
- Script version: 3.2.4

**Describe the bug**

I installed the app on my Nvidia Shield TV (Android TV 11) and wanted to try it out. But every time when I open the app, my Shield TV switches my TV to 480p resolution. So everything looks low-res and blurry. When I press the home button and exit the app, it switches back again to my previous setting (1080p 60Hz, as I don't have a 4K TV yet).

I guess this is caused by the app's feature to limit the screen refresh rate. When I open the app, it wants to adjust display mode. And then decides to pick just 480p60 for some strange reason. And this happens although my Shield TV is already set to 60HZ output when I open the app.

The feature to limit the screen refresh rate makes sense on phones and tablets. But I think not on Android TV devices. And I could imagine that it will also cause issues for other users. 

So I think it's not good that this feature is always on for all users. Without an option to disable it if it does cause problems. So if possible, please add a toggle for it, so I can just turn it off. 

Thanks.

**Comment by KingNothing81** [comment]
Do you use this API to limit refresh rate?
https://developer.android.com/media/optimize/performance/frame-rate

> Usage for games or other non-video apps
>
>Although video is the primary use case for the setFrameRate() API, it can be used for other apps. For example, a game that intends to not run higher than 60Hz (to reduce power usage and achieve longer play sessions) can call Surface.setFrameRate(60, Surface.FRAME_RATE_COMPATIBILITY_DEFAULT). In this way, a device that runs at 90Hz by default will instead run at 60Hz while the game is active, which will avoid the judder that would otherwise occur if the game ran at 60Hz while the display ran at 90Hz.

**Comment by redphx** [comment]
What does it say in the `Supported Display Modes` of the [DisplayInfo app](https://play.google.com/store/apps/details?id=com.drhowdydoo.displayinfo)

**Comment by KingNothing81** [comment]
![PNG-Bild](https://github.com/redphx/better-xcloud-android/assets/146887651/dfbee1d7-43b2-42a7-bfb9-c2dca24cbe6c)

**Comment by KingNothing81** [comment]
Horizontal and vertical resolution are twisted. I guess because it’s a phone app. 

So when I start the BxC app, I always get switched to 720x480@60Hz. Maybe because it’s the lowest resolution that supports 60Hz.

There are some media player apps on Android TV that also support refresh rate switching (like Kodi). But all have an in-app toggle for it. And have it disabled by default. 

So I’m happy trying to investigate this. But I still think that this feature should only be optional.

**Comment by redphx** [comment]
[com.redphx.betterxc_0.2b-2.apk.zip](https://github.com/redphx/better-xcloud-android/files/14635583/com.redphx.betterxc_0.2b-2.apk.zip)

This version disables this feature on all Android TV

**Comment by KingNothing81** [comment]
Ok. Thanks. I will give it a try soon.

**Comment by KingNothing81** [comment]
Sorry for the delay. I tried the test version now. But it still happens. The app still switches to 480p when I open it.

But I wonder why it only switches to 480p when I’m in the browser. Why does it even switch back to 1080p when I just go into the app’s settings menu? And back to 480p again when exit the settings screen. This is so weird.

But if you are sure that the feature to force 60Hz is disabled now on Android TV devices, I guess it must be something else that is causing this on my setup.

**Comment by redphx** [comment]
It was a bug. Fixed in 0.3
