### ISSUE TITLE
[Bug] my Rt and Lt doesn't work 

### ISSUE THREAD

**Issue by ChazyChazz** [redphx/better-xcloud-android#151]
### Device

Phone/Tablet

### Device name

Poco F5

### Android Version

14

### App version

0.22.0

### Script version

The last one? I don't know i new on this app but I didn't find the version 

### WebView name and version

Android system WebView 130.0.6723.107

### Reproduction Steps

I don't know what happens but my Controller it was normal but someday I entered in the app and the app doesn't recognize Lt and Rt button and the buttons it's working I tested in another apps And games

**Comment by redphx** [comment]
Which controller?  

1. Go to app settings, open Gamepad tester link. If it doesn't work then it's your hardware problem.  
2. Go to app settings, disable Bx script and try again. If it doesn't work then it's xCloud problem.

**Comment by ChazyChazz** [comment]
My controller is a bsp d6 I try do what you say but didn't work, it's weird because In the normal app the buttons work but I prefer your app because is so much better

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by redphx** [comment]
Reset your device or try to do something else. This is not Better xCloud's bug.
