### ISSUE TITLE
[Bug] Shortcut button disappeared

### ISSUE THREAD

**Issue by piersandro** [redphx/better-xcloud-android#153]
### Device

Phone/Tablet

### Device name

Logitech G Cloud

### Android Version

11

### App version

0.22.0

### Script version

5.9.7

### WebView name and version

Android System WebView 126.0.6478.246 (Thorium)

### Reproduction Steps

**Shortcut** button disappeared from game page to create new shortcut on device home screen.

![telegram-cloud-photo-size-4-5926955410378572794-y](https://github.com/user-attachments/assets/fc312f4e-be5a-4736-94af-8809f3ec7e9b)

**Comment by redphx** [comment]
Fixed in the latest beta version of the script

**Comment by redphx** [comment]
Fixed in script 6.0.1
