### ISSUE TITLE
[Bug] Native mouse feel laggy

### ISSUE THREAD

**Issue by farika** [redphx/better-xcloud-android#158]
### Device

Phone/Tablet

### Device name

S10 ultra

### Android Version

14

### App version

0.22.2

### Script version

6.06

### Reproduction Steps

1) Enable native Mouse and Keyboard
2) Try with a game compatible (halo infinite)

The mouse is a logitech M650L connected on a S10 ultra tablet with bluetooth
There is a lot of latency when using the mouse. It is unplayable with a lag sensation.
The issue is only on better xcloud, i don't have the issue on the system
Same when using a xbox / ds4 controller , no issue.
Tried to reduce or increase sensibility but the slider have no effect. 

Ping 30 MS. DT Around 14ms. CPU Dimensity 9300+.

Thanks

**Comment by redphx** [comment]
I dont have this problem

**Comment by farika** [comment]
I think this issue is linked that i have a very big decode time of 15ms. All seems very laggy.
Cpu mediatek dimensity 9300+.


Envoyé de mon mobile
Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by avlis84** [comment]
I also noticed a lot of lag in the mouse, even increasing the sensitivity

**Comment by hyde119** [comment]
https://github.com/user-attachments/assets/6a84351b-79a7-49c7-a695-4f186abc0a1b

This might be more wide spread than initially thought. Video above shows the mouse natively vs being captured by the app. 

- Z Fold 6
- Samsung DeX
- NexDock LapDock
- Wired mouse
- Running mouse natively (in app setting)
