### ISSUE TITLE
Bug when connecting a second controller or mouse

### ISSUE THREAD

**Issue by NatanaelRM** [redphx/better-xcloud-android#17]
**Platform** Android TV
- Device name: Realme TV Stick
- Device type (phone/TV): TV
- Android version: 11
- App version: 0.1
- Script version: 3.2.4

**Describe the bug**
Within the Android app, when I'm in the game and connect a second controller or mouse to play or configure the extension, the app simply reloads the xcloud page.

https://github.com/redphx/better-xcloud-android/assets/163755053/e81d91be-ee62-4a02-a3c1-dda311b30e42

**Comment by redphx** [comment]
Will be fixed in the next version

**Comment by redphx** [comment]
Fixed in 0.2
