### ISSUE TITLE
[Bug] Login from unknown foreign IP in my Microsoft account after logging in with Android app

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud-android#18]
**Platform**
- Device name: Shield TV
- Device type (phone/TV): Android TV 
- Android version: 11
- App version: 0.1
- Script version: 3.2.4

**Describe the bug**
After logging in on my Microsoft account with the BxC Android app, there is now a login from an unknown IP address from the Netherlands in my account activity. But I’m located in Germany. And the IP address shown in my account activity is not my current IP assigned from my ISP.

I tried to reproduce this and logged out and in again using the app. And got another entry in my account. Again from an unknown IP from the Netherlands. So this is really caused by the login using the Android app.

Logging in with another device shows my current German IP address as expected. So I wonder why this happens. And I have to admit that this also raises a little bit of security concerns.

**Comment by redphx** [comment]
Do you really think that I'm stealling your password?  
The app use this website for remote log in: https://xbox.com/play/login/deviceCode  

Try it yourself

**Comment by KingNothing81** [comment]
> Do you really think that I'm stealling your password? The app use this website for remote log in: https://xbox.com/play/login/deviceCode
> 
> Try it yourself

No, I’m not thinking that. 

I now tried to login using the device code method on another device. And yes, this will also show up as a login from the Netherlands.

So I will close that bug again. And sorry. It was not my attention to sound like I was thinking that you would do something fraudulent.
