### ISSUE TITLE
[Bug] App oppened in fullscreen mode

### ISSUE THREAD

**Issue by silvaa01** [redphx/better-xcloud-android#20]
**Platform**
- Device name: Motorola Moto G7 Power (ocean)
- Device type (phone/TV): phone
- Android version: 14
- App version: 0.2
- Script version: 3.2.4

**Describe the bug**

_After update, the app it goes beyond the camera cut-out and is completely full screen. Please make the app behave like this only in landscape mode._
**TOO YOU CAN'T SEE THE STATUS BAR WHEN RUNNING.**

**Screenshots/Videos**
![IMG_20240317_225548_109](https://github.com/redphx/better-xcloud-android/assets/111314382/ec4ce212-418e-4425-bd46-619ad20e1ebc)
![Screenshot_20240317-225915_BetterXC](https://github.com/redphx/better-xcloud-android/assets/111314382/5513d719-71bf-4d18-964e-279c15a6ddee)

**Comment by silvaa01** [comment]
Partially corrected

**Comment by redphx** [comment]
Fixed in 0.3
