### ISSUE TITLE
[Bug] Updating via in-app doesn't work

### ISSUE THREAD

**Issue by fortifying** [redphx/better-xcloud-android#22]
**Platform**
- Device name: Poco F4
- Device type (phone/TV): Android
- Android version: 13
- App version: 0.1
- Script version: ..

**Describe the bug**
Updating via app making the app just force close and not do anything, i don't know if *0.2* version  has fixed this.

**Screenshots/Videos**
https://github.com/redphx/better-xcloud-android/assets/60229681/3b1f8c5a-8791-48f7-8f60-a93d826fabd0

**Comment by KingNothing81** [comment]
I also ran into this. But when I opend my file manager and looked into the download folder, I saw that the app actually donwloaded the APK file for the update. But it didn't show the prompt asking if you want to install it, But just closed.

I think to make this work you have to go to Settings > Security > Unknown Sources. And allow the BxC app to install apps from unknown sources by toggling the switch.

**Comment by phantomdenied** [comment]
Can confirm this also happens on Meta Quest 2. The app force closes and does not update.

**Comment by redphx** [comment]
It should be fixed in 0.3

**Comment by fortifying** [comment]
Sorry for late reply, here's the log
[betterxc-log.txt](https://github.com/redphx/better-xcloud-android/files/14652086/betterxc-log.txt)

**Comment by redphx** [comment]
Thanks for the log. Now I know what caused it.

**Comment by redphx** [comment]
It should work with versio 0.4
