### ISSUE TITLE
FPS Drop - Achievements [Bug] ...

### ISSUE THREAD

**Issue by DragonJok** [redphx/better-xcloud-android#23]
Hello. Thanks for the full screen display solution. Can the problem of frame rate drops when receiving achievements be resolved without restarting the game? The game runs at 60 frames, sometimes, after receiving an achievement, the frames are reduced to 45, and after receiving a new achievement, the frames become at the level of 60 frames. Is it possible to disable these achievements altogether? This was observed in the browser, in the application.
![IMG_20240318_114820](https://github.com/redphx/better-xcloud-android/assets/163681582/5817df26-f866-44ec-bcec-88c99e37f356)

**Comment by redphx** [comment]
This is a known xCloud bug. The achievement is server-side and cannot be disabled by Better xCloud. Open the Guide menu (Xbox button) or reconnect to the game usually fix it.
