### ISSUE TITLE
Frame rate - 30 | 60 [Feature]

### ISSUE THREAD

**Issue by DragonJok** [redphx/better-xcloud-android#25]
Good time. The application requires the same amount of energy as the kiwi browser. But I like the VPN script, it’s responsive, it’s easier to launch for gameplay, that’s why this application is a top option. Question about frames, does the official application offer 30 frames? Only your development gives gameplay 60 frames if the game supports them? Can you make a frame rate choice? Standard - 30 frames. Unlocked - 60 frames. 30 frames uses less power, but just keep video frames as standard to keep gameplay smooth at 30 frames.

**Comment by redphx** [comment]
Not possible
