### ISSUE TITLE
[Bug] Android TV screen flickering

### ISSUE THREAD

**Issue by Batchuk** [redphx/better-xcloud-android#29]
**Platform**
Android tv
...

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by redphx** [comment]
Try this version

[com.redphx.betterxc_0.3-3.apk.zip](https://github.com/redphx/better-xcloud-android/files/14657603/com.redphx.betterxc_0.3-3.apk.zip)

**Comment by redphx** [comment]
Your device's H.264 encoder is buggy. Nothing I can do about that.
