### ISSUE TITLE
compatibility with android 7 (firestick)

### ISSUE THREAD

**Issue by jvpoke** [redphx/better-xcloud-android#3]
**I'm using:**  
- Device name: ...Firetv
- Device type (phone/TV): ...firestick
- Android version: ...7.1
  
**I want to suggest this feature:**  
...
compatibility with android 7 (firestick)

**Comment by redphx** [comment]
The device is too old and slow. It won't be able to play xCLoud anyway.

**Comment by jvpoke** [comment]
ok, one more clarification in the case with 2gb of using the emotn browser I have a good performance in 1080P in browsers with support for better xcloud xbrowser berrybrowser kiwi they are also very good but using other video tools and the clarity boost then yes it becomes impossible, in any case thanks to the app and your attention
