### ISSUE TITLE
18:9 aspect ratio [Feature]

### ISSUE THREAD

**Issue by DragonJok** [redphx/better-xcloud-android#30]
- Device name: Poco X3 Pro
- Device type (phone/TV): Phone
- Android version: 11
  
Good time. Can you add a new 18:9 aspect ratio? Displaying the image on full screen makes the characters and cars stretched out, this spoils the visual style a little. The 18:9 aspect ratio will make the image less stretched, adding only thin black bars, which visually looks more correct than full-screen mode.
You have added 16:9, 16:10, 4:3, 21:9, Full Screen to the application. Add another 18:9? Thank you.
![IMG_20240320_081728](https://github.com/redphx/better-xcloud-android/assets/163681582/184375ea-9bc1-483d-833d-8af6d99bb3e2)
![IMG_20240320_081840](https://github.com/redphx/better-xcloud-android/assets/163681582/8f461219-a69d-4509-b6c5-92d52f625f12)

**Comment by redphx** [comment]
Added. Go to app's settings > update better xcloud script to update it.
