### ISSUE TITLE
[Bug] Grey overlay appears over screen when physical controller is activated 

### ISSUE THREAD

**Issue by voxdub** [redphx/better-xcloud-android#32]
**Platform** Android 
- Device name: Ayn Odin2
- Device type (phone/TV): Handheld console
- Android version: 13
- App version: 0.4
- Script version: ...

When controller is activated a grey overlay appears over app screen making colours dull and washed out. Issue only present in app, running better xcloud in Kiwi browser is fine. 

...

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by redphx** [comment]
Please provide a video.  

Does it happen in the app's Settings screen?  

Please check which verison of Android System WebView app you have.

**Comment by voxdub** [comment]
Doesn't happen in setting screen, webview version is 101.0.4951.61

https://github.com/redphx/better-xcloud-android/assets/112777118/7f13a311-7cc3-4199-98f4-12f5c8346569

**Comment by redphx** [comment]
101.x is too old.

Try updating the Android System WebView app, either on Play Store or APKMirror. The current version is 122.x

**Comment by voxdub** [comment]
Updated to latest version but no change sadly, even uninstalled and reinstalled and tried v0.3 but does the same thing. It's not a major issue for me as have installed via Kiwi but very strange.

**Comment by redphx** [comment]
Open the script's Settings, then click on the Help button to go to the homepage. Only then activate the gamepad, and see if it still happens on other pages.

**Comment by voxdub** [comment]
Yep sadly still happens, I should probably test on another device, am assuming this is probably unique to Ayn Odin 2, hopefully isn't experienced across the board as the app makes it brilliantly simple for those less tech savvy to use better xcloud on Android, appreciate your support as always

**Comment by redphx** [comment]
Try this one: [com.redphx.betterxc_0.4-4.apk.zip](https://github.com/redphx/better-xcloud-android/files/14711839/com.redphx.betterxc_0.4-4.apk.zip)

This is the first time I hear about this bug.

**Comment by redphx** [comment]
@voxdub did you test with the latest version?

**Comment by voxdub** [comment]
Yep still persists on latest version

**Comment by redphx** [comment]
Try to disable the "force 60hz refresh rate" setting

**Comment by redphx** [comment]
@voxdub try this version: https://we.tl/t-bJbU3P35JB

**Comment by voxdub** [comment]
Amazing that's fixed it, I was gonna reply today as it seemed like just an Odin 2 issue as tested on phone and tablet and couldn't replicate with any external controllers on those. But whatever you've done in this version of the app it doesn't put a grey overlay over screen, thanks and hopefully it's prevented potential similar issues for others

**Comment by redphx** [comment]
fixed in 0.7
