### ISSUE TITLE
[Bug] Decoding time too high

### ISSUE THREAD

**Issue by Daniel908** [redphx/better-xcloud-android#33]
**Platform**
- Device name: Samsung Galaxy M31
- Device type (phone/TV): Phone
- Android version: 12
- App version: 0.4
- Script version: 3.2.5

**Describe the bug**
When I try remote play, this happen, The DT oscillates a lot, going from 5/8 ms to 30/40 ms sometimes.

**Screenshots/Videos**
![Screenshot_20240321-185736_BetterXC.jpg](https://github.com/redphx/better-xcloud-android/assets/22086403/c44ffbab-d9fe-4e02-81ed-c2026dae4581)

**Comment by redphx** [comment]
#41
