### ISSUE TITLE
[Bug] FPS between 30 or 0.

### ISSUE THREAD

**Issue by Lukinhasdacasual** [redphx/better-xcloud-android#34]
**Platform**
- Device name: Samsung Galaxy A13
- Device type (phone/TV): Phone
- Android version: 14
- App version: 0.4
- Script version: 3.2.4

**Describe the bug**
Hello! I'm a Better XCloud user in Brazil. The bug I want to report is the poor performance of the application. I know it was released these days, but it seems to be a bug, even because I play Fortnite and the FPS is stuck at 60 and in Forza Horizon 5, FIFA 23 the FPS is between 30 or drops to 0.

**Comment by redphx** [comment]
#41
