### ISSUE TITLE
[Bug] ... 

### ISSUE THREAD

**Issue by XxRafaelxX25** [redphx/better-xcloud-android#39]
**Platform** Android TV 
- Device name: ... Smart TV Philips 32 Android TV - 32PHG6918.
- Device type (phone/TV): ... TV 
- Android version: ... 11
- App version: ... 
- Script version: ...

**Describe the bug**
When you click select the app closes 

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

https://github.com/redphx/better-xcloud-android/assets/164700652/4be54c7e-2401-4a1d-b5e0-1987952d0f48

**Comment by redphx** [comment]
#38
