### ISSUE TITLE
Add Fullscreen App for Android device, Poco X3 Pro?

### ISSUE THREAD

**Issue by DragonJok** [redphx/better-xcloud-android#4]
**I'm using:**  
- Device name: ...
- Device type (phone/TV): ...
- Android version: ...
  
**I want to suggest this feature:**  
...

**Comment by redphx** [comment]
?

**Comment by DragonJok** [comment]
> **I'm using:**
> 
> * Device name: ...
> * Device type (phone/TV): ...
> * Android version: ...
> 
> **I want to suggest this feature:** ...

Poco X3 Pro
Phone
Android 11

**Comment by DragonJok** [comment]
> ?

Is it possible to add an aspect ratio with two black SMALL lines on the sides? So that the image is more correct, similar to the original, but at the same time takes up most of the screen.
![IMG_20240317_083635](https://github.com/redphx/better-xcloud-android/assets/163681582/ce0ad637-b28e-4bde-9060-95ebd40b7dbd)
![IMG_20240317_083333](https://github.com/redphx/better-xcloud-android/assets/163681582/493a6326-2795-4bbf-b105-d6a1cebd538a)
![IMG_20240317_083200](https://github.com/redphx/better-xcloud-android/assets/163681582/1b1ad0f9-b62d-499e-a240-456248cf8261)
![IMG_20240317_083021](https://github.com/redphx/better-xcloud-android/assets/163681582/9a4b3231-4619-497d-abe9-149cd297b6ea)

**Comment by DragonJok** [comment]
![IMG_20240317_084245](https://github.com/redphx/better-xcloud-android/assets/163681582/eae4fc76-ba7c-4d4e-bfcc-c6d676b00de1)
![IMG_20240317_084326](https://github.com/redphx/better-xcloud-android/assets/163681582/d1692fd9-6c06-4667-be81-812c45f90998)

**Comment by redphx** [comment]
Will be fixed in the next version

**Comment by DragonJok** [comment]
> Will be fixed in the next version

Poco X3 Pro, 20:9 aspect ratio. Stretching a picture to full screen makes it wider and flattened because the smartphone screen is elongated. Is it possible to add a not quite full screen? The 16:9 format is standard and has black bars on the sides, but they make the picture smaller. Golden mean - A picture with thin black lines on the sides, this is the one on the left, is it possible to add the same one on the right? The result will be an aspect ratio of 18:9 or some other. Would you like to experiment with this?

**Comment by redphx** [comment]
Fixed in 0.2  

About your suggestion, suggest it on better-xcloud repo
