### ISSUE TITLE
[Bug] Gamepad issues on Fire TV Lite

### ISSUE THREAD

**Issue by daviplutao** [redphx/better-xcloud-android#40]
**Platform**
- Device name: FireTV Lite
- Device type (phone/TV): Android TV
- Android version: I don't remember, but I think it's version 9
- App version: 0.5
- Script version: 3.3.0 (I think this is the most recent one)

**Describe the bug**
The gamepad I use is quite generic, very generic indeed. On the phone, this bug doesn't happen, but on the FireTV Lite it does. The bug is like this: "Start" and "Select" don't work. The Start button works to open that pop-up of "settings/gamepad tester/exit", but that's WITHIN THE RUNNING GAME. I don't understand because it's only on the FireTV that this happens; there's no such problem on the phone. And the "Select" doesn't work at all.

**Screenshots/Videos**
[The video I recorded is uploaded to the drive, I can't send it here because it's too big](https://drive.google.com/file/d/13VKGiphw0nnqym0tD_NQQ1_HLI9v9t93/view?usp=drivesdk)

**Comment by redphx** [comment]
Test the controller with the Gamepad Tester menu.

**Comment by daviplutao** [comment]
> Teste o controlador com o menu Gamepad Tester.

I edited the post and adding a video link to Google Drive if you can see it would help. I've already tested it, and it works. In the Xbox app, all buttons work normally.

**Comment by PRENJUTIRENG** [comment]
> Test the controller with the Gamepad Tester menu.

i had same problem on my phone poco x5 and gamepad with xinput,no problem on original xbox gamepass app but in better xcloud the right analog and start and select doesnt work,please add button remapping or fix it so i could play 2 player with stable resolution and bitrate please.

**Comment by daviplutao** [comment]
> @daviplutao try this version [com.redphx.betterxc_0.9.0-11.apk.zip](https://github.com/redphx/better-xcloud-android/files/14850852/com.redphx.betterxc_0.9.0-11.apk.zip)

The bug persists. I do not know what to do. My controller is a Wireless Controller X3.


https://github.com/redphx/better-xcloud-android/assets/70152718/f0d58e8d-ac5c-4ea9-a945-760427032315

**Comment by daviplutao** [comment]
I accidentally closed my problem, I apologize The bug persists. I do not know what to do. My controller is a **Wireless Controller X3**. **"Start"** opens this pop-up and if I click on **"Start"** again it closes it. But, I can close the popup on the **"Select"** button. It returns any page I open, for example.

https://github.com/redphx/better-xcloud-android/assets/70152718/adc1de1e-bce1-4d9b-b092-66695e6a9ef3

**Comment by H34M35** [comment]
hello, sorry for my English and thank you for better xcloud. I use the app on my phone and it works very well and on my TV with an Nvidia shield pro 2019. With the Nvidia shield the select button of my Xbox controller doesn't work, it isn't recognize on The game pad tester. Can you do something? thank you for your work :-)

**Comment by H34M35** [comment]
the same Xbox controller works very well when I play with my phone.

**Comment by KingNothing81** [comment]
> With the Nvidia shield the select button of my Xbox controller doesn't work, it isn't recognize on The game pad tester. Can you do something?

@H34M35: Hi ... this is a Shield TV specific issue. Please read my post here to solve this:
https://github.com/redphx/better-xcloud-android/issues/81#issuecomment-2068211274

@daviplutao: And I think the gamepad problems on the Fire TV are caused by a simliar issue: Amazon remapping controller buttons on a system level to make using the device with a gamepad feel more comfortable. "Real" apps can override this. But it will cause problems when trying to use xCloud in a web browser or WebView (like with the BXC app). But I don't know a solution for this for Fire TV devices.

**Comment by daviplutao** [comment]
> olá, desculpe pelo meu inglês e obrigado pelo xcloud melhor. Eu uso o aplicativo no meu celular e funciona muito bem e na minha TV com um Nvidia Shield Pro 2019. Com o Nvidia Shield o botão de seleção do meu controle do Xbox não funciona, não é reconhecido no testador de game pad. Você pode fazer algo? obrigado por seu trabalho :-)



> olá, desculpe pelo meu inglês e obrigado pelo xcloud melhor. Eu uso o aplicativo no meu celular e funciona muito bem e na minha TV com um Nvidia Shield Pro 2019. Com o Nvidia Shield o botão de seleção do meu controle do Xbox não funciona, não é reconhecido no testador de game pad. Você pode fazer algo? obrigado pelo seu trabalho :-)

**Comment by daviplutao** [comment]
> olá, desculpe pelo meu inglês e obrigado pelo xcloud melhor. Eu uso o aplicativo no meu celular e funciona muito bem e na minha TV com um Nvidia Shield Pro 2019. Com o Nvidia Shield o botão de seleção do meu controle do Xbox não funciona, não é reconhecido no testador de game pad. Você pode fazer algo? obrigado pelo seu trabalho :-)

Answer by DAVIPLUTO: This problem is probably because of the control.

**Comment by KingNothing81** [comment]
I already told user @H34M35 how to solve this issue on Shield TV:
https://github.com/redphx/better-xcloud-android/issues/81#issuecomment-2068211274

And I suspect that Amazon is doing something similar on Fire TV. But I don’t know if and how this modification could be disabled on Fire OS.
