### ISSUE TITLE
HarmonyOS

### ISSUE THREAD

**Issue by Razer3k** [redphx/better-xcloud-android#43]
Huawai Matepad T10s
AGS3K-W09

Version 0.2 works fine, but no higher version does. Can  I replace Android System View, because Can not  legally install Google apps. Can something be done about it?

**Comment by KingNothing81** [comment]
Maybe try to sideload it?
https://www.apkmirror.com/apk/google-inc/android-system-webview/

**Comment by redphx** [comment]
`Version 0.2 works fine` = does it show Better xCloud's settings?

**Comment by Razer3k** [comment]
Yes, better xcloud work

**Comment by redphx** [comment]
Capture a video showing the app in version 0.2

**Comment by Razer3k** [comment]
https://github.com/redphx/better-xcloud-android/assets/164740041/03294e3d-c52f-442f-99db-9711052fe4c3

**Comment by redphx** [comment]
I didn't see a button with server's name in the video

![image](https://github.com/redphx/better-xcloud-android/assets/96280/f970c76b-b456-45fc-a61a-1afeda13a833)

**Comment by Razer3k** [comment]
Ehh. You're right, it doesn't work at the moment. However, APK version 0.2 still works. Unfortunately, all of the above does not want to move

**Comment by redphx** [comment]
Move to #55
