### ISSUE TITLE
[Bug] control does not vibrate on fire stick tv.

### ISSUE THREAD

**Issue by Marcio009** [redphx/better-xcloud-android#44]
Normal fire stick TV, I can't apply vibration to the control.
it only appears that it was selected, but it doesn't work
![17112804134971999840549505269219](https://github.com/redphx/better-xcloud-android/assets/163761570/c1e6850d-3a9a-461c-a90b-170b22d1b918)

**Comment by redphx** [comment]
Check vibration support using the Ganepad Testing link in the menu.  

It it shows `Vibration: N/A` then either Firestick TV or WebView doesn't support it.
