### ISSUE TITLE
[Bug] I can't press to select options. Tv fire stick

### ISSUE THREAD

**Issue by Marcio009** [redphx/better-xcloud-android#45]
I can't select the options, and the normal Fire Stick TV appears this dark color in the options, making it difficult to see from afar.

https://github.com/redphx/better-xcloud-android/assets/163761570/ad3425a7-e696-4e86-9dfc-f86751df35cf

**Comment by redphx** [comment]
Fixed in 0.6.1

**Comment by Marcio009** [comment]
did not work
