### ISSUE TITLE
[Bug] Problems when the game interface appears on the Fire Stick TV.

### ISSUE THREAD

**Issue by Marcio009** [redphx/better-xcloud-android#46]
the interface doesn't appear, I can only hear the sound, but it works when the game is opened. Normal TV fire stick.

https://github.com/redphx/better-xcloud-android/assets/163761570/a648d7e6-5cfd-44e4-93fb-4f874e09172c

**Comment by redphx** [comment]
Which version is this? Why didn't you fill the form I put there.

**Comment by redphx** [comment]
Re-download v0.6.1 and try again

**Comment by Marcio009** [comment]
did not work

**Comment by redphx** [comment]
If this still happens, create a new issue with more info
