### ISSUE TITLE
[Bug] No Sound with Sonos

### ISSUE THREAD

**Issue by Martinomac** [redphx/better-xcloud-android#47]
**Platform**
- Device name: NVidia Shield TV Pro
- Device type (phone/TV): Sony Bravia with Sonos Beam
- Android version: Shield TV SW version 9.1.1 (33.2.0.157)
- Current app version: 0.6.1
- Last working app version: no sound since 1st beta
- Script version: ...

**Describe the bug**
When opening any games on BetterXC on NVidia Shield, I get no sound. My soundbar works as I’ve tried increasing volume but does not help. In e exiting app, sound works with other applications. 

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by redphx** [comment]
- Try using TV speakers only, make sure it's the stream's problem and not hardware's  
- When connecting to a game, open the ... menu, then share me the photo of that screen (with all the info badges)

**Comment by Martinomac** [comment]
![IMG_8308](https://github.com/redphx/better-xcloud-android/assets/4346908/98d5c000-d6b3-4e1e-b24c-34bdc567a4cc)
![IMG_8371](https://github.com/redphx/better-xcloud-android/assets/4346908/15aa8331-0745-469e-9670-434546f95a31)

The above is with v0.10.1, Chrome web view, checked audio/video sync option. The game runs fine, just no audio.

I have sound with GeForceNow app and no audio lag.  Unfortunately, no audio from xCloud Android on Shield.
