### ISSUE TITLE
[Feature] Add a Page Zoom Option

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud-android#48]
- Device name: Shield TV
- Device type (phone/TV): Android TV
- Android version: 11
  
Using the Android app on a 1080p TV, everything on the screen feels a little bit big.

![Bxcloud](https://github.com/redphx/better-xcloud-android/assets/146887651/351e6273-e42c-4287-8731-274ae7331f16)

Using Kiwi I was able to use the page zoom option to adjust my view. I set it to 80%, which looks way better I think.

![Kiwi](https://github.com/redphx/better-xcloud-android/assets/146887651/470306a6-8ca2-4bef-ac7d-157bbcbbd0d7)

So as the app will be used on devices with many different screen sizes and resolutions, I think adding a page zoom option would be a nice feature for many users. So they can adjust the view to their liking.

**Comment by redphx** [comment]
Have you tried Layout > TV?

**Comment by KingNothing81** [comment]
Yes … I tried the Smart TV layout. But then everything is even bigger. I guess because it’s I optimized for TVs with 4K resolution.

![Smarttv](https://github.com/redphx/better-xcloud-android/assets/146887651/697eb428-2b3b-41ca-b042-c7bb23b53dd1)

I also tried the other UA profiles, but couldn’t see a difference compared to using the default UA.

Personally I would even like to hide the tool bar. Like you can set auto hide for the taskbar on a desktop OS. But I don’t know if this would be even possible on Android.

**Comment by KingNothing81** [comment]
Sorry for getting a little off topic here ... but about hiding the toolbar:

Do you already know the app "Fully Kiosk Browser"?
https://play.google.com/store/apps/details?id=de.ozerov.fully

It's also a little web browser using the System Webview. And has a ton of options to adjust things.

And it uses an app menu that slides in from the left side. You can open it by swiping on touch devices or by long pressing the back button on Android TV (or menu button if you have one). 

![fully1](https://github.com/redphx/better-xcloud-android/assets/146887651/6b941fbc-6401-456a-ac9e-ffcc24dab78b)

If someone wants it, it's also possible to show an additional tool/address bar in the web browser. But it's only optional. Because at the moment the problem with hiding the tool bar on the BXC app would be that people can't go into the app settings anymore. So this could be a solution for that. Especially for Android TV users. Because at the moment I can't use the tool bar buttons with a remote or controller. I have to enable my mouse app.

The app also has many other interesting features. So maybe you want to check it out and see if you find something you like. And that can be an inspiration for improving the BXC app. =)

**Comment by redphx** [comment]
added in 0.7
