### ISSUE TITLE
[Bug] Stream of the game is flickering

### ISSUE THREAD

**Issue by alecman3000** [redphx/better-xcloud-android#49]
- Device name: Sony Bravia KD-55X75K
- Device type (phone/TV): Android TV
- Android version: Android TV OS 11
- Current app version:  Version 0.6.1
- Last working app version: N/A
- Script version: Updated to latest on settings.

After the rocket animation and xbox logo, every stream of the games flickers. it's like going back and forth on the frames.
Tested games Yakuza 3, Persona 3 and palworld.

https://github.com/redphx/better-xcloud-android/assets/41981287/5c5bfd54-d73f-4992-b58f-8fb2ac0cc83e

https://github.com/redphx/better-xcloud-android/assets/41981287/741e7930-7e36-4d1e-aa37-37409b5235c2

**Comment by redphx** [comment]
Check #41
