### ISSUE TITLE
Microphone and other improvements

### ISSUE THREAD

**Issue by SamComeli** [redphx/better-xcloud-android#5]
**I'm using:**  
- Device name: Redmi Note 9s
- Device type (phone/TV): Phone
- Android version: 12
  
**I want to suggest these features:**  

- **Enable microphone for games**

![Screenshot_2024-03-16-17-30-25-013_com redphx betterxc](https://github.com/redphx/better-xcloud-android/assets/80470057/02d37ca9-df62-45d4-86ca-0313fb9e4e7c)

- **Prevent the app from restarting when connecting a controller**, (it's annoying because it closes the game, which doesn't happen in the Kiwi browser)

- **Create the option for games to enter popup mode when leaving the app**, (it's a feature that I think is very good in browsers, it prevents the game from closing, which is good when you need to do something else on your phone without worrying about loading the game again)

**Comment by redphx** [comment]
1. Fixed
2. Fixed

**Comment by redphx** [comment]
3. Create a separate issue
