### ISSUE TITLE
[Bug] Screen error issue during remote play

### ISSUE THREAD

**Issue by Leapseatiger** [redphx/better-xcloud-android#50]
hello. I'm enjoying the app you developed. But there's one problem. I am using your app with my Logitech G Cloud. Even if you use the latest versions of Kiwi Browser, apps, and scripts, errors sometimes appear on the screen. However, what is unpredictable is that this error does not occur all the time, but occurs intermittently. Normal operation is possible, I hear sound, but only the screen shows an error. When this problem occurs, the same screen error occurs in the XBX Play app, and in the official Xbox app, only a black screen is displayed and there is no sound. Can you help me solve this problem?
![Screenshot_20240320_225406_Photos](https://github.com/redphx/better-xcloud-android/assets/164822401/8e5136be-6b06-44fd-ac0a-5da721ce5ef4)

**Comment by Leapseatiger** [comment]
Cloud games can run normally. The problem only occurs with remote play.

**Comment by redphx** [comment]
This is problably caused by packet loss. Make sure the console is connected to ethernet, NAT is open, and all necessary ports are opened: https://better-xcloud.github.io/remote-play/
