### ISSUE TITLE
[Bug] Echo sound

### ISSUE THREAD

**Issue by DragonJok** [redphx/better-xcloud-android#51]
- Device name: Poco X3 Pro
- Device type (phone/TV): phone
- Android version: 11
- Current app version: The freshest

Good time. Better xCloud app. If you collapse it and expand it again, an echo of the game sound appears, which is corrected by restarting. Can you fix this?

**Comment by redphx** [comment]
Do you use the "volume control" feature?

**Comment by DragonJok** [comment]
> Используете ли вы функцию «регулятор громкости»?

In the settings of better xCloud there is a checkbox for volume control.
