### ISSUE TITLE
[Feature] Support other WebView implementations

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud-android#55]
The current version only supports Android System WebView implementation.  
I'm working on a workaround that might work on all kind of WebView implementation.

[How to use custom WebView implementation](https://github.com/redphx/better-xcloud-android/wiki/Custom-WebView-implementation)

[Check which implementation the device is using](https://chromium.googlesource.com/chromium/src/+/master/android_webview/docs/prerelease.md#switch-channel) then share that info in a comment below (with screenshot is a plus).

**Comment by Tak-attack** [comment]
Device: Black Shark 4 (Android 11)
122.0.6261.119
![IMG_20240330_115705](https://github.com/redphx/better-xcloud-android/assets/149154024/618074ad-553a-49dc-8fc7-69668d469190)

**Comment by redphx** [comment]
Added in 0.10.0

**Comment by KingNothing81** [comment]
Would it be possible to also add support for the Thorium browser (Thorium_Public_xxx.apk)? Like you did with Chrome Stable/Beta/Canary. This way there would be no conflict with the "com.android.webview" system package. And more people could give Thorium a try.

**Comment by redphx** [comment]
No, because it doesn't contain the WebView library.

**Comment by KingNothing81** [comment]
Playing around with the flags, I noticed that there is "WEBVIEW_SURFACE_CONTROL" and "WEBVIEW_SURFACE_CONTROL_FOR_TV". And the description of the first one says: "Is not supported for TV, see WebViewSurfaceControlForTV." This might be relevant for Android TV devices.

**Comment by SantosCFillipe** [comment]
When I configure the new WebView Complement, and restart the app, the app doesn't open and I need to remove the data app, I tested and configuring de  Thorium or WebView Native occurred the same error, do you know something about? I'm using Chromecast 4 With Android Tv.
