### ISSUE TITLE
[Bug] Top bar visible at all times in Samsung Dex mode

### ISSUE THREAD

**Issue by sirlagg** [redphx/better-xcloud-android#56]
**Platform**
- Device name: Samsung Galaxy S23 Ultra
- Device type (phone/TV): phone
- Android version: 14
- Current app version: 0.6.1
- Last working app version: 0.6.1
- Script version: 3.3.0

**Describe the bug**
In Samsung Dex mode, the top bar (address bar) does not hide when entering a game, in is always visible even when the game is supposed to be at full screen.

**Comment by redphx** [comment]
video pls
