### ISSUE TITLE
[Bug] App crashing when opened

### ISSUE THREAD

**Issue by silvaa01** [redphx/better-xcloud-android#57]
**Platform**
- Device name: Motorola Moto G7 Power (ocean)
- Device type (phone/TV): Phone
- Android version: 14
- Current app version: 0.7-8
- Last working app version: 0.6.1
- Script version: 3.3.0

**Describe the bug**
...

**Screenshots/Videos**

https://github.com/redphx/better-xcloud-android/assets/111314382/6e24db37-8c67-4884-870d-f978cc69c52b

[crash-com-redphx-betterxc-31-03_12-06-50.zip](https://github.com/redphx/better-xcloud-android/files/14816899/crash-com-redphx-betterxc-31-03_12-06-50.zip)

**Comment by redphx** [comment]
Fixed in 0.7.1
