### ISSUE TITLE
[Bug] On Android TV: Toolbar gets unreachable after moving around on xCloud website

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud-android#59]
- Device name: Shield TV
- Device type (phone/TV): Android TV
- Android version: 11
- Current app version: 0.7

The problem is that once you start using the remote/controller to move around on the xCloud website, it’s not possible to get back to the toolbar anymore.

Here is a video …

https://github.com/redphx/better-xcloud-android/assets/146887651/c80c6a69-2ebc-455c-ba74-e59986a7fd0e

At the beginning of the video you can see that when I open the app, I can still use my remote/controller to interact with the toolbar.

But once I go down and start moving around on the xCloud website, I can’t go back the toolbar anymore. You can see that at the end of the video where I’m at the top of the xCloud website. And try to get back to the toolbar by pressing up again. But I can’t reach it, no matter if I try it on the left or right side of the screen. 

That’s not a new issue. It’s there since the first version. But I wanted to wait before I report it. To see if it might be already fixed after the first updates.

P.S.: And thanks a lot for adding the page zoom option. It’s really appreciated. =)

**Comment by redphx** [comment]
can't be fixed until the app uses native UI

**Comment by KingNothing81** [comment]
Hm, ok. I thought that this issue might not be fixable. It's like the xCloud website captures control, so there is no way back.

But would it be possible to auto hide the toolbar as soon as you move down to the xCloud website? Because if the toolbar gets unreachable anyway, it would be nice if it would hide itself.

I use "Button Mapper" to send "open app menu" when long pressing the "Start" button on my controller. This way I can open the app's menu (that one on the right behind the three dots) and go to the settings screen without needing the toolbar. Other Android TV users that have a remote with a "Menu" button could do the same. 

So maybe the ability to hide the toolbar could be an additional option for Android TV users that don't want/need to have the toolbar on the screen.
