### ISSUE TITLE
It lags a bit on my phone

### ISSUE THREAD

**Issue by Starmew-p** [redphx/better-xcloud-android#6]
**Platform**
- Device name: Redmi Note 8
- Device type (phone/TV): Phone
- Android version: 10
- App version: 0.1

**Describe the bug**
The games are a bit laggy and have some delay with the controllers, they are not impossible to play on, but it is frustrating sometimes. The fps fluctuates between 15-30 fps. I could play on normal xcloud since it runs smoothly, but i have no 5G connection, so the quality is the worst.

**Comment by redphx** [comment]
#41
