### ISSUE TITLE
[Bug] The game image doesn't appear and neither does the rocket.

### ISSUE THREAD

**Issue by Marcio009** [redphx/better-xcloud-android#61]
**Platform**
- Fire tv stick full HD
- better xcloud version 0.8.0

**Describe the bug**
The rocket doesn't appear, neither does the image of the game to open it and the Xbox logo, I didn't deactivate them in the configuration.  I use Fire TV stick full HD

https://github.com/redphx/better-xcloud-android/assets/163761570/7b057ed9-6783-4a12-803c-2c3eead09d9b

https://github.com/redphx/better-xcloud-android/assets/163761570/798c2e93-bc14-45b7-a663-6a7cd1d9ad51

https://github.com/redphx/better-xcloud-android/assets/163761570/32842b86-09bf-4b4f-aff4-0ccf642656e0

**Comment by redphx** [comment]
More likely xCloud's problem
