### ISSUE TITLE
[Bug] Some games drop FPS

### ISSUE THREAD

**Issue by Marcio009** [redphx/better-xcloud-android#62]
**Platform**
- Fire stick full HD
- better xcloud version 0.8.0

**Describe the bug**
Some games like Persona 3 Reload, The Quarry version of Xbox one and Evil West the FPS drops, while other games like Plague Tale Requiem, Resident Evil Remake 1 and 2 work normally with the same settings.  I tried lowering the settings to minimum for evil west and it still dropped FPS.  I tried forcing 60 hz and it remains the same.

**Comment by redphx** [comment]
#41
