### ISSUE TITLE
[Bug] The option to play with vibration on the controller does not work

### ISSUE THREAD

**Issue by Marcio009** [redphx/better-xcloud-android#63]
**Platform**
- TV fire stick full HD 
- better xcloud version 0.8.0
- Control xbox series S
 
**Describe the bug**
My controller is an xbox series S, but I activate the vibration and it doesn't go, I play on the fire stick full HD and play with Bluetooth, I don't feel latency

**Comment by redphx** [comment]
Firestick's problem
