### ISSUE TITLE
[Feature] IMPORTANT FOR BETTER PERFOMANCE

### ISSUE THREAD

**Issue by Kashe89** [redphx/better-xcloud-android#64]
**I'm using:**  
- Device name: Noblex Android TV
- Device type (phone/TV): Android TV
- Android version: 10
  
**I want to suggest this feature:**  
... Let us enable the Parallel Downloading from Chrome://flags, i enabled this on my kiwi browser and i can't play without it because this thing increases a lot the PERFOMANCE so please add this option for the Better Xcloud App

**Comment by redphx** [comment]
WebView doesn't have this feature. And don't use uppercase in title.
