### ISSUE TITLE
[Feature] Ability to open the app menu with the controller (and let controller users always hide the toolbar)

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud-android#65]
- Device name: Shield TV
- Device type (phone/TV): Android TV
- Android version: 11
  
Here is a video showing how I open the app’s menu and settings with my controller.

https://github.com/redphx/better-xcloud-android/assets/146887651/db1a78b2-1c0b-4301-b3ce-98738248dd21

I do this with the “Button Mapper” app. That is set to send key code “82” (=KEYCODE_MENU) when I long press the “Start” button. 

https://elementalx.org/button-mapper/android-key-codes/

This works when I’m on the xCloud website, but as I wanted to show in the video, this also works during gameplay when the toolbar is hidden.

So I wanted to suggest to add direct support for this in the Android app. So it will work for all users without having to use “Button Mapper”. 

And if it’s possible to access the app’s settings this way, it would also be no problem to allow controller users to always hide the toolbar. This way the app would look and feel even more native on a TV.

**Comment by KingNothing81** [comment]
I saw on your Telegram channel that you are about to remove the toolbar with the next version. Which I really like and why I will close that issue now.

But I thought that you want to place the Android app's settings button on top of the script settings. And now I saw on Telegram that it will be at the bottom right corner. And hide when you scroll down. But how to press that button with a controller? So I hope that you will also keep the button on top of the script setttings.

And as you know, the default Android TV launcher doesn't support the shortcut feature. But I'm also not aware of any custom Android TV launcher that would support that kind of shortcuts (if anyone does, please let me know). So maybe it would make sense to hide those new bottom right buttons on Android TV devices.

**Comment by redphx** [comment]
you have to use mouse with the current UI. There is no eay around it unless the app support native UI for Android TV

**Comment by KingNothing81** [comment]
Hm, but actually many things already work with just a controller and/or remote. And I can do my daily usage things without a mouse. 

And I thought that placing the “Android App Settings” button on top of the script settings was a very good idea. Because there it’s indeed possible to reach and press it with a connected controller. So I hope you can keep it. To have an **additional** way to open the app settings that also works without touch/mouse.

**Comment by KingNothing81** [comment]
One last idea I wanted to share before I will stop being that one annyoing Android TV user again. ;)

Every Android (TV) device has a "Back" button (under/on screen, on the remote). So pressing that "Back" button could open a dialog box at the middle of the screen. And that has all needed options, like "App Settings", "Quit App", etc.. Even the toolbar buttons (Home/Go Back/Refresh) could live on in that box, as you could only use the icons and place them all in one row.

Using such a dialog box should work on all devices, no matter if they have touch support or not. Without the need to place additional buttons on the main screen. So maybe that could be something to consider.
