### ISSUE TITLE
[Bug] After playing and closing the video in full screen, the toolbar disappears.

### ISSUE THREAD

**Issue by Tak-attack** [redphx/better-xcloud-android#67]
**Platform**
- Device type: Phone
- Current app version: 0.9.0
- Script version: 3.4.0

**Describe the bug**
When playing a trailer or other video on each game page, the toolbar at the top of the screen goes full screen, but the toolbar remains off after closing it with the close button.

Furthermore, if "Force landscape mode when playing" is turned on, the screen is fixed in landscape mode when you return.

https://github.com/redphx/better-xcloud-android/assets/149154024/ea14eebb-d4ab-4bb3-851b-55acc70751af

**Comment by redphx** [comment]
Fixed. Go to app's Settings > Update Better xCloud script to fix it.
