### ISSUE TITLE
Crash game EA PGA Tour [Bug]

### ISSUE THREAD

**Issue by DragonJok** [redphx/better-xcloud-android#68]
**Platform**
- Device name: Poco X3 Pro
- Device type (phone/TV): phone
- Android version: 11
- Current app version: Latest version

**Describe the bug**
Good time. EA PGA Tour game crashes when connecting to Electronic Arts servers.

**Screenshots/Videos**
https://github.com/redphx/better-xcloud-android/assets/163681582/20dbdb3e-5495-4d38-9039-5c9cd3c5b109

**Comment by redphx** [comment]
Report it to Xbox

**Comment by DragonJok** [comment]
> Report it to Xbox

I found this problem with the game itself on the Internet, but it says that you need to run the game in windowed mode, the developers released a fix, but in fact the game does not connect to the Electronic Arts servers. Error on the developers' side? their other games connect.

**Comment by DragonJok** [comment]
Try running this game? On the latest version of your application.
