### ISSUE TITLE
[Bug] Fortnite won't load...

### ISSUE THREAD

**Issue by HunterNatsu** [redphx/better-xcloud-android#69]
**Mobile**
- Device name: Samsung Galaxy A01
- Device type (phone/TV): Phone
- Android version: 12
- Current app version: 0.10.0
- Last working app version: 0.9.0
- Script version: N/D

**Describe the bug**
Fortnite loads the screen and everything else, the rocket goes across the screen and the message "preparing your game" appears but it stays like that for hours, I spent 3 hours waiting for it to load.

**Screenshots/Videos**
![Screenshot_20240406-231425](https://github.com/redphx/better-xcloud-android/assets/166270812/39794ec9-47a5-4848-9fcf-0263d63fb61c)

**Comment by redphx** [comment]
xcloud problem
