### ISSUE TITLE
[Bug] Problems with the FPS of some games

### ISSUE THREAD

**Issue by Marcio009** [redphx/better-xcloud-android#70]
**Platform**
- TV fire stick full HD
- Version 0.10.0

**Describe the bug**
Until a few days ago I was having problems with Evil West, it didn't even work with everything at least, but with this update to change the webview, it's working in 1080p and normal visuals, calm down, but Persona 3 Reload still suffers from problems.  other games like Resident Evil 2 and 3 remake and Plague Tale work perfectly at 1080p.  What still suffers is the recharging of Persona 3, I believe it is not a problem with the fire stick, I know that an update to optimize it would be better.  I used the booster and Death Stranding works without crashes and that's because I live in Brazil with Ping at 100.

**Comment by redphx** [comment]
Try setting Touch control's availability to Off

**Comment by Marcio009** [comment]
> Tente definir a disponibilidade do Touch Control como desligado

Ok, I will update you with any improvements I have

**Comment by Marcio009** [comment]
> Tente definir a disponibilidade do Touch Control como Desligado

hi, I saw if it worked by doing this, it still remains the same way, when I enter the area where persona 3 fights, it only works if I leave it at 720p with low visuals, the other games are working, at least the ones that I tested it as resident and evil west

**Comment by redphx** [comment]
the device can only handle low bitrate scenes  

#41
