### ISSUE TITLE
[Bug] App keeps force closing

### ISSUE THREAD

**Issue by t00noob** [redphx/better-xcloud-android#71]
**Platform**
- Device name: Sony Xperia XZ2
- Device type: Phone
- Android version: 10
- Current app version: v0.10.1
- Last working app version: v0.9.0
- Script version: 3.5.0

**Describe the bug**
The issue happens when i've closed/force stop the app after i changed the WebView implementation to Chrome 123.0.6312.81

**Comment by redphx** [comment]
https://github.com/redphx/better-xcloud-android/wiki/Custom-WebView-implementation
