### ISSUE TITLE
[Bug] Region Button Unclickable

### ISSUE THREAD

**Issue by 000Samuel000** [redphx/better-xcloud-android#72]
**Platform**
- Device name: OnePlus 9
- Device type (phone/TV): Phone
- Android version: 15
- Current app version: 0.10.1
- Last working app version: N/A
- Script version: 0.10.1

**Describe the bug**
Region Stuck on " " and can't click due to how html works maybe you could implement

**Potential Solution**
Checking if it's innerText is blank and if it is sets the region to a random server so it's changeable on userscript reload

**Comment by redphx** [comment]
Try app's Settings > Update Better xCloud script

**Comment by 000Samuel000** [comment]
Didn't work
