### ISSUE TITLE
Freeze [Feature]

### ISSUE THREAD

**Issue by DragonJok** [redphx/better-xcloud-android#73]
Device name: Poco X3 Pro
Device type (phone/TV): phone
Android version: 11
Current app version: Latest version

Good time. The application or browser extension begins to freeze after some time. In the browser this is less noticeable, after some time the freezes go away, are these lags of the Internet or the script connection? The ping during freezes is good, the bitrate is also good, packet loss is minimal, all values ​​are the same with and without freezes, this started recently, with some kind of update.

**Comment by redphx** [comment]
- this is a bug report, not feature request
- check your network
