### ISSUE TITLE
[Bug] “Unhandled Thrown Error!” when opening Xbox Guide Menu

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud-android#76]
### Device

Other

### Device name

Shield TV

### Android Version

Android TV 11

### App version

0.11.0

### Script version

3.5.2

### WebView name and version

Android System WebView 123

### Reproduction Steps

When opening the Xbox Guide during gameplay, I’m getting an “Unhandled Thrown Error!” message as shown in the screenshot.

![PNG-Bild](https://github.com/redphx/better-xcloud-android/assets/146887651/e17183d2-213a-4a58-98e3-e666e47b6eca)

This didn’t happen with the previous version of the Android app. And it doesn’t happen with the current script version when using Kiwi Browser. So I think it’s a bug in the Android app.

**Comment by redphx** [comment]
xCloud's bug. It happens randonly.

**Comment by redphx** [comment]
Android WebView doesn't support [`navigator.permissions` API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/permissions), so when the website tries to call `navigator.permissions.query()` you'll get that error. We have to wait for them to fix this bug.  
Or you can use Chrome WebView.

**Comment by KingNothing81** [comment]
Thanks for the tip. It's indeed not just random for me, but permant. I tried it many times in the last days. Also with setting Chrome as WebView implemantation. Actually I was using Chrome when the error came up. And than I switched to the Android System WebView before I made the bug report. And it always happens when using the Android app. But never happens when trying it at the same time with Kiwi. 

Leaving the guide open when starting a game, it seems to me that the error shows up in that moment when the "muted microfone" icon shows up in the guide's bottom bar when using Kiwi.

The strange thing is that when they intially rolled out the preview, the new guide still worked without that problem. So it must be the lastest update to the xCloud website that has caused this for me.

If this is not a permant issue for you with the Android app, can you tell me which Chrome version you are using as WebView?

**Comment by KingNothing81** [comment]
Looks like the xCloud team already fixed it. The error message doesn’t show up anymore, even when using the default “Android System WebView”.
