### ISSUE TITLE
[Bug] Better Xcloud Tcl TV 

### ISSUE THREAD

**Issue by drporcoaranha** [redphx/better-xcloud-android#77]
### Device

TV

### Device name

TCL TV Android 

### Android Version

11

### App version

0.11.0

### Script version

3.5.3

### WebView name and version

Android System view 124.0.6367.54

### Reproduction Steps

Open any game in Android Apk 

https://github.com/redphx/better-xcloud-android/assets/167335779/1de8e872-8ae2-45f1-8f88-45c9c426c29a

The games present this error in the image that apparently is lost frames.
I changed Webview for all version (Beta, canary and chrome) and the erro remains.
In kiwi works 100%.

**Comment by redphx** [comment]
#41
