### ISSUE TITLE
"Optimization of Amazon Fire TV"

### ISSUE THREAD

**Issue by Resplays** [redphx/better-xcloud-android#78]
### Device

Other

### Device name

Fire tv stick 4k max

### Android Version

9

### Suggestion

Optimization of the application for Fire TV Stick, with frequent freezes and slowness, is crucial, as TV boxes offer better cost-effectiveness and are more commonly used. I would appreciate it if you could address this issue; lately, it's been impossible to even play.

**Comment by KingNothing81** [comment]
I don't know if it works on FireOS, but maybe you could try to follow this guide to set Chrome as your WebView implemenation?

Using the default "Android System WebView" worked quite well on my device, but using Chrome feels just a little bit more smooth and responsive. So maybe it can also help improve your experience.

**Comment by Resplays** [comment]
Sure, here's the translation: "I've already tried this, but it does improve a bit, yet still with crashes and slowness."

**Comment by Resplays** [comment]
I've already tried this, but it does improve a bit, yet still with crashes and slowness.

**Comment by KingNothing81** [comment]
> How do you install the apk in Fire Tv? I download It with Downloader App but It can't install. The system informs a problem in package analisys.

Are talking about the BXC app or Chrome?

**Comment by daniellb04** [comment]
> > How do you install the apk in Fire Tv? I download It with Downloader App but It can't install. The system informs a problem in package analisys.
> 
> Are talking about the BXC app or Chrome?

BXC app

**Comment by Resplays** [comment]
The app I use for this is...

**Comment by Resplays** [comment]
I use the app for this. BXC

**Comment by redphx** [comment]
It won't be supported/improved unless the app stops using WebView
