### ISSUE TITLE
Apk analysis problem on Fire TV

### ISSUE THREAD

**Issue by daniellb04** [redphx/better-xcloud-android#79]
I can't install the better xcloud apk on my Fire TV 4K. It informs that occurs a problem in package analysis. I tried three last releases of the apk. Can anyone help me?

**Comment by Resplays** [comment]
I download APKs on my phone and transfer them to the TV stick using an app: send fires to tv

**Comment by daniellb04** [comment]
> I download APKs on my phone and transfer them to the TV stick using an app: send fires to tv

I transfer the apk from different ways. It always fail to install showing the message: "There was a problem parsing the package"

**Comment by redphx** [comment]
It requires Android 8+
