### ISSUE TITLE
[Feature] Launch App in landscape mode

### ISSUE THREAD

**Issue by NekomimiNebula** [redphx/better-xcloud-android#82]
### Device

Phone/Tablet

### Device name

OnePlus 6T

### Android Version

11

### Suggestion

I mainly use this app with my Backbone controller, and obviously it's held in landscape mode. So I would like there to be a feature where the app can open in landscape mode by default and then I don't need to flip my phone up to navigate through the menu.

**Comment by redphx** [comment]
Added in 0.14.0
