### ISSUE TITLE
[Bug] Performance degradation since 0.10 

### ISSUE THREAD

**Issue by magicsgram** [redphx/better-xcloud-android#83]
### Device

Phone/Tablet

### Device name

Amazon Fire HD 10 (2019 Edition)

### Android Version

9

### App version

0.11

### Script version

Not sure

### WebView name and version

Android System WebView 120

### Reproduction Steps

**My Device:**

- It's a 5-year-old device with low specs, even at the time of purchase.
- The Kiwi browser had extremely poor performance for xCloud, so I switched.

**xCloud Performance:**

- After installing version 0.6, xCloud worked perfectly (both cloud and remote) at 1080p/60fps with very little delay. This was a pleasant surprise!
- It functioned very well until version 0.9. Unfortunately, starting with version 0.10 (and the current version 0.11), the performance has dropped significantly (around 20-40 fps).

**Workaround and Questions:**

- I can reinstall version 0.9 to regain full performance, but then I won't receive updates, and it will likely break eventually.
- Have there been any major changes to how webviews are handled since version 0.10? I understand the option to choose a webview was added, but I only have one installed, and it's probably the same one used in version 0.9. This is why I'm unsure what changed.

By the way, thank you so much for such a wonderful project!!

**Comment by redphx** [comment]
Do you have "Amazon System WebView"?

**Comment by magicsgram** [comment]
I've got

Amazon System WebView
120.amazon-webview-v120-6099-tablet.6099.266.53

I tried changing user agent to "Safari + mac OS" and the performance is back to normal. The one that gave me trouble was Edge + Windows.

I don't know what actually changes w/ user agent, but things seems crisp and responsive!

Thanks.

**Comment by redphx** [comment]
What happen if you use Default profile?

**Comment by magicsgram** [comment]
> What happen if you use Default profile?

It's a hit or miss. It would run for 60fps for 10 seconds, than like 15-30fps for another 10 seconds, then back to 60 fps for "X" seconds, and back to 15-30 for "Y" seconds.

Safari + mac OS seems be the most stable one for now, w/ only few stutters here and there, but nothing major. Again, my Fire HD 10 is 5 year old and low speced. So that's expected.

I'm just glad that I'm even able to resurrect my old machines and use betterxcloud with the app, which Kiwi browser couldn't provide!

**Comment by redphx** [comment]
Thanks for the discovery, but it still feels so random to me. I need to find out why.

**Comment by Resplays** [comment]
![IMG_20240501_011003](https://github.com/redphx/better-xcloud-android/assets/164455537/9e845c33-4e0b-4120-af2d-f84c928e2b0e)
