### ISSUE TITLE
[Bug] Remote play still doesn't work 

### ISSUE THREAD

**Issue by BigFrog666** [redphx/better-xcloud-android#85]
### Device

Phone/Tablet

### Device name

Poco X3 NFC

### Android Version

12

### App version

0.12.0

### Script version

4.0.1

### WebView name and version

Android System WebView 123.0.6312.120

### Reproduction Steps

https://github.com/redphx/better-xcloud-android/assets/163888827/2a423799-d117-40ee-badf-773914ca30ad

![IMG-20240424-WA0084](https://github.com/redphx/better-xcloud-android/assets/163888827/2842789c-1dad-478d-997f-b548faac84b1)

The remote play function doesn't work if I'm on a different network than the Xbox even though all the router ports are open. It works perfectly on the official Xbox app, but on the Better xcloud app, for some reason, it doesn't. I've tried several things, including using a public ip, but nothing worked. 

I don't know if this will help anything, but I'm from Brazil and the Internet here is a little different, for example, from the United States. Anyway I would really like to be able to use the script for remote play, so please ask for attention to this problem.

**Comment by redphx** [comment]
Dup https://github.com/redphx/better-xcloud-android/issues/27
