### ISSUE TITLE
[Bug] i can not update the app after 0.90

### ISSUE THREAD

**Issue by DocS788** [redphx/better-xcloud-android#86]
### Device

Phone/Tablet

### Device name

Google Pixel 7a

### Android Version

14

### App version

0.11

### Script version

Updated

### WebView name and version

Latest

### Reproduction Steps

- open the app
- prompt reminds me to update the app, 
- update and it does not install it, it says package installer error ( I have given the access to installation from unknown resources)
[Log_2024-05-02_13-48-58.txt](https://github.com/redphx/better-xcloud-android/files/15187872/Log_2024-05-02_13-48-58.txt)

**Comment by redphx** [comment]
Uninstall everying and download the APK again from GitHub
