### ISSUE TITLE
Quest 2 Remote Play screen won't refresh unless it's being "touched" by the quest contoller[Bug] 

### ISSUE THREAD

**Issue by ghostfnk** [redphx/better-xcloud-android#88]
### Device

Other

### Device name

Meta Quest 2

### Android Version

12

### App version

0.12.0 (15)

### Script version

n/a

### WebView name and version

Latest 125.x beta

### Reproduction Steps

Everything works really well, perfect 1080p, no input lag from Xbox controller. But when using the remote play feature, the screen won't refresh unless I'm "touching" (pressing the Quest controller trigger button) on the screen.

There is a fix for this exact issue with the Xbplay app (https://www.reddit.com/r/xbPlay/wiki/index/) by changing the render engine.

Is there anything I can do to fix this? Better xCloud is so much better than Xbplay because their controller lag is huge. But obviously Better xCloud is unusable if the screen won't refresh.

**Comment by redphx** [comment]
Please show a video demonstrating the problem

**Comment by ghostfnk** [comment]
![F38D929B-30DD-4FDF-8271-823CE0614FC7_1_102_o](https://github.com/redphx/better-xcloud-android/assets/168864231/6d4849ad-ce64-4ffc-86fc-83ab848ae55f)

**Comment by ghostfnk** [comment]
https://youtu.be/1tHsYsxbuAM

thanks for your work!

**Comment by redphx** [comment]
xCloud doesn't have this issue right? I think I have an idea how to fix it.

**Comment by ghostfnk** [comment]
Correct. Both xCloud and Xbox android app don't have this issue.

**Comment by redphx** [comment]
Try this version: https://github.com/redphx/better-xcloud/raw/typescript/dist/better-xcloud.user.js  

I added "Meta Quest VR" User-Agent profile. Not sure it will help in this case, but at least it will disable touch controller.

**Comment by ghostfnk** [comment]
The new profile removes all the visuals of the touch controller but the problem remains. The Quest controller still needs to be "touching" the window for the screen to not be stuck.

ICYMI in the OP: a similar app by the name Xbplay suffers from this exact issue but there is an option to change the "render engine" that solves it. The options are "WebView, geckoview, Chrome".

In Xbplay, WebView is the one that causes this same stuck-screen issue as in Better xCloud. Switching it to either geckoview or Chrome fixes it.

Hope this helps!!

**Comment by Learner00100** [comment]
> UPDATE: I got it working! The trick is when you're using a Meta Quest 2 device to run Better xCloud, after changing the WebView implementation to 'Android System WebView Beta' (downloaded the apk from Aurora Store) you must RESTART the entire Quest 2 headset, not just restart the app. After the headset restart is when Better xCloud makes the change. Controller vibration also works perfectly.
> 
> You likely just need the latest version of Android Webview but I went with the Beta because it was easiest to install from Aurora Store.
> 
> And yes the new profile indeed disables the visuals for the touch controller, which is helpful. I'll be donating a coffee or two ASAP. Thank you again for your work!

Can you able to get controller vibration in other android device?
