### ISSUE TITLE
[Feature] Add option to hide the new on-screen buttons

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud-android#93]
### Device

TV

### Device name

Shield TV

### Android Version

Android TV 11

### Suggestion

I updated to version 0.13 now, and this is how things look on my setup now.

![IMG_0256](https://github.com/redphx/better-xcloud-android/assets/146887651/d07ef611-badd-4a99-bf61-af32e6ae49f4)
![IMG_0256](https://github.com/redphx/better-xcloud-android/assets/146887651/2f48db8f-0bfb-4f08-ae0d-77bb13493a9a)

First I was surprised that there is an additional refresh button. Because I thought that the app supports “pull to refresh” now. So is the refresh button there by intention or just a bug? Because I can’t spot it on your shared screenshots on Telegram.

And another thing: With my used zoom factor (80%), the page won’t scroll down already when you are in the “Jump back” row. So the settings button is still there and covers the “controller hints“ that are also displayed at the bottom right corner when a controller is connected. 

So of course the on-screen buttons are more visible to the user. But once people know about the other “app settings” button above the script settings and don’t want to use the home shortcuts feature, some might like to be able to hide those on-screen buttons. 

So maybe that’s something you could consider for a future update. Thanks.

**Comment by redphx** [comment]
The refresh button only shows on Android TV devices. And you still need a mouse to use it.
