### ISSUE TITLE
[Feature] Add a white theme in the settings page

### ISSUE THREAD

**Issue by silvaa01** [redphx/better-xcloud-android#96]
### Device

Phone

### Device name

POCO X3 (karna)

### Android Version

14

### Suggestion

Add a white theme to the app settings page, along with a "follow device theme" function. This would make it easier to read in sunlight. Thanks for your dedication.

![Screenshot_20240529-094827_Better_xCloud](https://github.com/redphx/better-xcloud-android/assets/111314382/af85856d-39f5-4886-b781-e360fe9c2131)

**Comment by redphx** [comment]
Added in 0.16.0
