### ISSUE TITLE
[Bug] Option to force the app to work at up to 60hz is not working

### ISSUE THREAD

**Issue by silvaa01** [redphx/better-xcloud-android#97]
### Device

Phone/Tablet

### Device name

POCO X3 (karna)

### Android Version

14

### App version

0.15.0

### Script version

4.6.0

### WebView name and version

Android System WebView Dev 127.0.6493.0

### Reproduction Steps

I used an FPS counter to make it possible to understand.

https://github.com/redphx/better-xcloud-android/assets/111314382/d92ef8d6-1a49-4430-9b95-5caff934b424

**Comment by redphx** [comment]
Does you phone support dynamic framerate? Apparently it only works in that mode.

**Comment by silvaa01** [comment]
It has 120hz.

**Comment by redphx** [comment]
Install this app and share the screenshots of the info: https://play.google.com/store/apps/details?id=com.drhowdydoo.displayinfo

**Comment by silvaa01** [comment]
> Instale este aplicativo e compartilhe as capturas de tela das informações: https://play.google.com/store/apps/details?id=com.drhowdydoo.displayinfo

![Screenshot_20240608-075953](https://github.com/redphx/better-xcloud-android/assets/111314382/d1dca42b-0dc7-4d46-859f-3fb73f7dc80e)

**Comment by silvaa01** [comment]
> Install this app and share the screenshots of the info: https://play.google.com/store/apps/details?id=com.drhowdydoo.displayinfo

![Screenshot_20240608-075953](https://github.com/redphx/better-xcloud-android/assets/111314382/0e3c76d4-1f28-4709-87a6-e4e1a40610a4)

**Comment by redphx** [comment]
This feature doesn't always work. Changed the setting's text to "Prefer 60hz refresh rate".
