### ISSUE TITLE
[Bug] Page layout issues after using the new “Back To Home” button

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud-android#99]
### Device

Other

### Device name

Shield TV

### Android Version

Android TV 11

### App version

0.15.1

### Script version

4.6.3

### WebView name and version

Chrome 125.x

### Reproduction Steps

Hi …

When using the new ‘Back To Home” button in the Guide menu to go back to the start page, the page will be shown at 100%, ignoring my zoom factor set in the app settings. And the green bottom right buttons won’t also show up again.

As I’m using the “Smart TV” profile, I also tried changing to the default profile to see if it makes a difference. But with the same result.

https://github.com/redphx/better-xcloud-android/assets/146887651/f92b4fde-f114-41df-8f81-4153cdc51082

**Comment by redphx** [comment]
Should be fixed in script 4.7.0
